### ISSUE TITLE
Canu error through RepLong: canu failed with 'gatekeeper store exists, but contains no reads' 

### ISSUE THREAD

**Issue by LuciaA2** [ruiguo-bio/replong#1]
Hi,

I'm trying to find repeated sequences in the genome of my bacteria through RepLong. When I execute the RepLong command in Linux, it starts to run until the following error appears:

=============================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'gatekeeper store exists, but contains no reads'.

temp/correction/1-overlapper/001/*.ovb
ERROR:  invalid arg 'temp/correction/1-overlapper/001/*.ovb'
usage: /home/carlos/Escritorio/Lucia/replong-master/canu-1.4/Linux-amd64/bin/overlapConvert [options] file.ovb[.gz]

  -G             gkpStore (needed for -coords, the default)

  -coords        output coordiantes on reads
  -hangs         output hangs on reads
  -raw           output raw hangs on reads

  -native        input ovb file is NOT snappy compressed

ERROR:  no overlap files supplied
filter overlap file to merge repeat
Traceback (most recent call last):
  File "/home/carlos/Escritorio/Lucia/replong-master/edge_1.py", line 87, in <module>
    outfilename)
  File "/home/carlos/Escritorio/Lucia/replong-master/edge_1.py", line 9, in buildEdgeWithFrom
    with open(overlapfile, 'r') as a, open(readlengthfile, 'r') as b,\
IOError: [Errno 2] No such file or directory: 'temp/correction/step2.gkpStore/reads.txt'
use community detection to merge repeat
Loading required package: methods

I followed all the instructions on your page, but it seems like the text file doesn't exists

Thank you very much,

Lucía

**Comment by bzvew** [comment]
Hi, Lucia. Can you find a file called replong.log under your folder when you run replong? I want to check that file.

**Comment by LuciaA2** [comment]
[replong.log](https://github.com/ruiguo-bio/replong/files/1855275/replong.log)

**Comment by bzvew** [comment]
When you run replong, can you log the running of RepLong to a file for me to check? You can do that by append the "&> test.log" to the command line when you run RepLong. And I want to check that test.log file. You should delete the temp folder of your previous run first. Thanks.

**Comment by LuciaA2** [comment]
[test.log](https://github.com/ruiguo-bio/replong/files/1867724/test.log)

Thanks.

**Comment by bzvew** [comment]
Hi, can you find a new.fa file under the folder /home/carlos/Escritorio/Lucia/replong-master/temp/?
If there is, what is the size of that file?

**Comment by LuciaA2** [comment]
Hi, the temp folder is automatically deleted when after running the script, but the file new.fa is generated in /home/carlos/Escritorio/Lucia/replong-master/. The size of this file is 0 B

**Comment by bzvew** [comment]
If possible, can you send me the reads1.fasta file for me to test that?

**Comment by LuciaA2** [comment]
can I send it by mail?.

I have reinstalled Canu but version 1.7 and now other things appear. I attach the file with the text. The first error is on line 567 "llegal division by zero at /home/carlos/Escritorio/REPLONG_nuevo/replong/canu-1.4/Linux-amd64/bin/../lib/site_perl/canu/Gatekeeper.pm line 485 . "

[text_canu1.7.log](https://github.com/ruiguo-bio/replong/files/1871443/text_canu1.7.log)

**Comment by bzvew** [comment]
Yes, if convenient, please send to ruiguo0225@gmail.com.

**Comment by bzvew** [comment]
I find it is the file name issue, and your file format is 
>m160216_153322_42244_c100951122550000001823215806251656_s1_p0/18/0_3761 RQ=0.843

before RQ there is a space, that will cause issue. I remove the RQ field from the input file and the program can run without error. I modify the program to keep new.fa(the file before merging similar reads) and result.fa(the file after merging) in case the result.fa is too small.

**Comment by LuciaA2** [comment]
Hi,
I have reinstalled everything, with the changes and with my data without spaces and now it returns another error. It's as if it can not find a file (the error is on line 734 of the text.log file): 
IOError: [Errno 2] No such file or directory: 'temp/correction/step2.gkpStore/reads.txt'

[text.log](https://github.com/ruiguo-bio/replong/files/1876646/text.log)

**Comment by bzvew** [comment]
In the log file it shows it is a mix between canu1.4 and canu1.7, and I don't know why it shows canu1.7 when you running canu under the canu1.4 folder. Can you delete the canu-1.4 folder under replong folder, and run ./install.sh again to make sure you only run canu1.4?

**Comment by LuciaA2** [comment]
I finally got it!.  I have changed to version 1.4 of Canu and now it works.

Thank you very much for your help

**Comment by jorisbertrand** [comment]
Hi,
it looks that I have a quite similar issue but I cannot solve it. Could you help me to try to figure out what  happens?
Cheers
[test.log](https://github.com/ruiguo-bio/replong/files/3072420/test.log)
